export const SEED_EXERCISES: { name: string; videoUrl: string; muscleGroup: string }[] = [
  { name: 'Press Banca', videoUrl: '', muscleGroup: 'Pecho' },
  { name: 'Press Inclinado', videoUrl: '', muscleGroup: 'Pecho' },
  { name: 'Aperturas', videoUrl: '', muscleGroup: 'Pecho' },
  { name: 'Fondos', videoUrl: '', muscleGroup: 'Pecho' },
  { name: 'Sentadilla', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Peso Muerto', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Prensa', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Zancadas', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Hip Thrust', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Extensión de Cuádriceps', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Curl Femoral', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Elevación de Gemelos', videoUrl: '', muscleGroup: 'Piernas' },
  { name: 'Press Militar', videoUrl: '', muscleGroup: 'Hombros' },
  { name: 'Elevaciones Laterales', videoUrl: '', muscleGroup: 'Hombros' },
  { name: 'Pájaros', videoUrl: '', muscleGroup: 'Hombros' },
  { name: 'Remo con Barra', videoUrl: '', muscleGroup: 'Espalda' },
  { name: 'Dominadas', videoUrl: '', muscleGroup: 'Espalda' },
  { name: 'Jalón al Pecho', videoUrl: '', muscleGroup: 'Espalda' },
  { name: 'Remo en Polea', videoUrl: '', muscleGroup: 'Espalda' },
  { name: 'Curl de Bíceps', videoUrl: '', muscleGroup: 'Brazos' },
  { name: 'Curl Martillo', videoUrl: '', muscleGroup: 'Brazos' },
  { name: 'Press Francés', videoUrl: '', muscleGroup: 'Brazos' },
  { name: 'Extensión de Tríceps', videoUrl: '', muscleGroup: 'Brazos' },
  { name: 'Plancha', videoUrl: '', muscleGroup: 'Core' },
  { name: 'Crunch', videoUrl: '', muscleGroup: 'Core' },
  { name: 'Burpees', videoUrl: '', muscleGroup: 'Full Body' },
];
